version: "3"
services:

  booking-dictionary-db:
    container_name: booking_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - booking-dictionary-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - booking-dictionary

  redis:
    image: redis:latest
    container_name: booking-dictionary-redis
    ports:
      - "6379:6379"
    networks:
      - booking-dictionary

volumes:
  booking-dictionary-data:

networks:
  booking-dictionary:
    name: booking-dictionary
    driver: bridge